// <auto-generated />
using System;
using AuctionData.Application.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuctionData.Application.Migrations
{
    [DbContext(typeof(AuctionDbContext))]
    partial class AuctionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("AuctionData.Domain.Auction.Auction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Bid")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Buyout")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ItemListingId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeLeft")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemListingId");

                    b.ToTable("Auctions");
                });

            modelBuilder.Entity("AuctionData.Domain.Auction.ItemListing", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("InternalBonuses")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ItemListing");
                });

            modelBuilder.Entity("AuctionData.Domain.Auction.Modifier", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ItemListingId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemListingId");

                    b.ToTable("Modifier");
                });

            modelBuilder.Entity("AuctionData.Domain.Auction.Auction", b =>
                {
                    b.HasOne("AuctionData.Domain.Auction.ItemListing", "ItemListing")
                        .WithMany()
                        .HasForeignKey("ItemListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemListing");
                });

            modelBuilder.Entity("AuctionData.Domain.Auction.Modifier", b =>
                {
                    b.HasOne("AuctionData.Domain.Auction.ItemListing", null)
                        .WithMany("Modifiers")
                        .HasForeignKey("ItemListingId");
                });

            modelBuilder.Entity("AuctionData.Domain.Auction.ItemListing", b =>
                {
                    b.Navigation("Modifiers");
                });
#pragma warning restore 612, 618
        }
    }
}
