// <auto-generated />
using System;
using AuctionData.Application.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuctionData.Application.Migrations
{
    [DbContext(typeof(AuctionDbContext))]
    [Migration("20231009193607_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("AuctionData.Application.Entities.Auction.Auction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Bid")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Buyout")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ItemListingId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeLeft")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemListingId");

                    b.ToTable("Auction");
                });

            modelBuilder.Entity("AuctionData.Application.Entities.Auction.AuctionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AuctionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RetrievedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.ToTable("AuctionLogs");
                });

            modelBuilder.Entity("AuctionData.Application.Entities.Auction.ItemListing", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("InternalBonuses")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ItemListing");
                });

            modelBuilder.Entity("AuctionData.Application.Entities.Auction.Modifier", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ItemListingId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemListingId");

                    b.ToTable("Modifier");
                });

            modelBuilder.Entity("AuctionData.Application.Entities.Item.Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("AuctionData.Application.Entities.Auction.Auction", b =>
                {
                    b.HasOne("AuctionData.Application.Entities.Auction.ItemListing", "ItemListing")
                        .WithMany()
                        .HasForeignKey("ItemListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemListing");
                });

            modelBuilder.Entity("AuctionData.Application.Entities.Auction.AuctionLog", b =>
                {
                    b.HasOne("AuctionData.Application.Entities.Auction.Auction", "Auction")
                        .WithMany()
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");
                });

            modelBuilder.Entity("AuctionData.Application.Entities.Auction.Modifier", b =>
                {
                    b.HasOne("AuctionData.Application.Entities.Auction.ItemListing", null)
                        .WithMany("Modifiers")
                        .HasForeignKey("ItemListingId");
                });

            modelBuilder.Entity("AuctionData.Application.Entities.Auction.ItemListing", b =>
                {
                    b.Navigation("Modifiers");
                });
#pragma warning restore 612, 618
        }
    }
}
